### ISSUE TITLE
Can you tell me how to make an addon for ic2 classic 1.19.2?

### ISSUE THREAD

**Issue by proxima812** [KubeJS-Mods/wiki#57]
example:

```js
// Изменение блока ic2:mass_fabricator
BlockEvents.modification(event => {
	// Проверяем, что это Mass Fabricator
	event.modify("ic2:mass_fabricator", block => {
		// Удаляем старые значения для сброса ограничений
		delete block.maxInput

		// Устанавливаем новый лимит входа энергии 2048 EU
		block.maxInput = 2048
	})
})

```

**Comment by Donaldino7712** [comment]
no

**Comment by proxima812** [comment]
> For KubeJS support, go to the server https://discord.gg/lat and get support with scripts

new link neded, this old

**Comment by wolfieboy09** [comment]
https://discord.com/invite/lat
that?

**Comment by proxima812** [comment]
> https://discord.com/invite/lat that?

the link has expired

**Comment by wolfieboy09** [comment]
https://discord.gg/lat 

it's not expired though

If that still fails, then try

https://discord.gg/wx84D2RB

(7 days valid for kjs server)

**Comment by proxima812** [comment]
> https://discord.gg/lat
> 
> но срок годности еще не истек
> 
> Если это все еще не удается, то попробуйте
> 
> https://discord.gg/wx84D2RB
> 
> (7 дней действительно для сервера kjs)

Strangely, he still writes that it has expired. What is the name of the server, I will find it by searching

**Comment by wolfieboy09** [comment]
what about this https://kubejs.com/support

also server name is latvian.dev

**Comment by proxima812** [comment]
> what about this https://kubejs.com/support
> 
> also server name is latvian.dev

That's it, I'm in. Thanks!

**Comment by wolfieboy09** [comment]
Okay, no clue why that happened

**Comment by wolfieboy09** [comment]
Did you join the right server?

**Comment by proxima812** [comment]
> Did you join the right server?

yes, of course
